version: "3"

services:
  couchdb:
    image: couchdb:3.3.2
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '5984:5984'
    expose:
      - '5984'
    volumes:
      - './couch_data:/opt/couchdb/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 30
      timeout: 10s
      retries: 3
  readingtree:
    build: .
    restart: unless-stopped
    volumes:
      - './static:/static'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30
      timeout: 10s
      retries: 3
    env_file:
      - ".env"
    expose:
      - '8080'
    depends_on:
      couchdb:
        condition: service_healthy
        restart: true
  webserver:
    image: caddy:2.7-alpine
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'
      - './caddy_data:/data'
